PDiddysPizzeria/Models/PizzaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PDiddysPizzeria.Models
{
  public class PizzaModel
  {
    public int id { get; set; }
    public string Name { get; set; }
    public Size Size { get; set; }
    public List<string> Toppings { get; set; } 
  }
}

PDiddysPizzeria/Models/Size.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PDiddysPizzeria.Models
{
  public class Size
  {
    public int Id { get; set; }
    public string Name { get; set; }
    public int NumberOfSlices { get; set; }
  }
}

PDiddysPizzeria/Controllers/CouponsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PDiddysPizzeria.Services;

namespace PDiddysPizzeria.Controllers
{
    public class CouponsController : Controller
    {
        //
        // GET: /Coupons/

        public ActionResult Index()
        {
          var customerOrderService = new CustomerOrderService();
          var customerName = customerOrderService.GetCustomerName(lastName: "Mason");
          var model = customerOrderService.GetCustomerOrderItems(5);
            return View();
        }

        //
        // GET: /Coupons/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Coupons/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Coupons/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Coupons/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Coupons/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Coupons/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Coupons/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PDiddysPizzeria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PDiddysPizzeria.Models;


namespace PDiddysPizzeria.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: www.pdiddyspizza.com/

        public ActionResult Index()
        {
            var myPizza = new PizzaModel();

            myPizza.Name = "Cheese Lovers";
            myPizza.Size = new Size{Id = 2, Name = "Medium", NumberOfSlices = 8};
            myPizza.Toppings = new List<string>();
            myPizza.Toppings.Add("Cheddar");
            myPizza.Toppings.Add("Feta");
            return View(myPizza);
        }

        //
        // GET: www.pdiddyspizza/Details/5

        public ActionResult Details(int id)
        {
          
            return View();
        }

        //
        // GET: /Home/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Home/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Home/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Home/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Home/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PDiddysPizzeria/Views/Coupons/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-md4">
        <h2>PDiddy's Coupons!</h2>
    </div>
    <div id="my-select-list-container" class="col-md4">
        <select id="ddlMyOptions" class="input-large">
            <option>test 1</option>
            <option>test 2</option>
            <option>test 3</option>
            <option>test 4</option>
            <option>test 5</option>
        </select>
    </div>
</div>

PDiddysPizzeria/Views/Home/Index.cshtml
@model PDiddysPizzeria.Models.PizzaModel
@{
    ViewBag.Title = "Index";
}

<h1>PDiddy's Pizzeria</h1>
<h2>Welcome to the home page</h2>
<h3>BuyPizza</h3>

<legend>Check out our Coupons</legend>

@Html.ActionLink("Click Here", "Index", "Coupons", new {}, new { @class = "btn btn-primary", id = "hypCouponsHome" })
<table>
    <tr>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>@Model.Size.Name</td>
    </tr>
    <tr>
        @foreach (var item in Model.Toppings)
        {
            <td>@item</td>
        }
    </tr>
</table>

PDiddysPizzeria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap/base")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <body>
        <div class="container">
            @RenderBody()
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>